name: Pipline CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21.0.3
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21.0.3'
          architecture: 'x64'


      - name: Build with Ant
        run: ant -f build.xml -Dj2ee.server.home = /home/runner/work/CinePa/nbproject/build-impl.xml

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /opt/tomcat/apache-tomcat-10.1.25/webapps/
            sudo rm -rf ROOT/
            sudo cp ~/CinePa/dist/CinePa.war ./ROOT.war  # Adjust path to your WAR file
            sudo systemctl restart tomcat
