name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Ant
      uses: aqztr/github-actions-ant@v1

    - name: Build with Ant
      run: ant clean compile

    - name: Test with Ant
      run: ant test

    - name: Package with Ant
      run: ant package

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        AWS_EC2_USER:  ${{ secrets.EC2_USER }}
        AWS_EC2_IP: ${{ secrets.EC2_HOST }}
        TOMCAT_WEBAPPS_DIR: '/var/lib/tomcat10/webapps'
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no dist/CinePa.war $AWS_EC2_USER@$AWS_EC2_IP:$TOMCAT_WEBAPPS_DIR
