name: Pipeline CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up JDK 21.0.3
      - name: Set up JDK 21.0.3
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21.0.3'
          architecture: 'x64'

      # Step to set the libs.CopyLibs.classpath property
      - name: Set libs.CopyLibs.classpath
        run: |
          ant -f build.xml -Dj2ee.server.home=/opt/tomcat -Dlibs.CopyLibs.classpath=lib/org-netbeans-modules-java-j2seproject-copylibstask.jar
        working-directory: /home/runner/work/CinePa/CinePa  # Set the correct working directory

      # Step to build the project using Ant with the server home directory specified
      - name: Build with Ant
        run: |
          ant -f build.xml -Dj2ee.server.home=/opt/tomcat -Dlibs.CopyLibs.classpath=lib/org-netbeans-modules-java-j2seproject-copylibstask.jar
        working-directory: /home/runner/work/CinePa/CinePa  # Set the correct working directory

      # Step to deploy the built WAR file to an EC2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /opt/tomcat/apache-tomcat-10.1.25/webapps/
            sudo rm -rf ROOT/
            sudo cp ~/dist/CinePa.war ./ROOT.war  # Adjust path to your WAR file
            sudo systemctl restart tomcat
